### ISSUE TITLE
regex constraints not working with nonexamples

### ISSUE THREAD

**Issue by nicholasf** [firebase/blaze_compiler#54]
Hi,

I'm trying to set up a regex constraint on a mobile phone number model, with examples and nonexamples. It appears that the nonexamples somehow pass erroneously. 

Here is a simpler example to illustrate the problem:

```
schema:
  definitions:
    red:
      type: string
      constraint: next.val().matches(/red/)
      examples:
          - "red"
      nonexamples:
          - "blue"
          - "green"

  type: object
  required: [users]
  properties:
    users:
      type: object
      $uid:
        properties:
          favourite_colour:
            $red: { $ref: "#/definitions/red" }

```

Output when running this:

```
♪  firebase-schema git:(master) ✗ blaze test.yaml -v
args { _: [ 'test.yaml' ], v: true, java: false, '$0': 'blaze' }
transpiling test.yaml

input:
{"schema":{"definitions":{"red":{"type":"string","constraint":"next.val().matches(/red/)","examples":["red"],"nonexamples":["blue","green"]}},"type":"object","required":["users"],"properties":{"users":{"type":"object","$uid":{"properties":{"favourite_colour":{"$red":{"$ref":"#/definitions/red"}}}}}}}}
Warning:  no access list defined, this Firebase will be inactive
loading type any definition from /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/../schema/metaschema/any.yaml
loading type boolean definition from /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/../schema/metaschema/boolean.yaml
loading type number definition from /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/../schema/metaschema/number.yaml
loading type object definition from /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/../schema/metaschema/object.yaml
loading type string definition from /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/../schema/metaschema/string.yaml
annotate_schema { type: 'object',
  '$uid': { properties: { favourite_colour: [Object] } } }
annotate_schema { '$red': { '$ref': '#/definitions/red' } }
fetchRef#/definitions/red retrieved {"type":"string","constraint":"next.val().matches(/red/)","examples":["red"],"nonexamples":["blue","green"]}
annotate_schema { type: 'string',
  constraint: 'next.val().matches(/red/)',
  examples: [ 'red' ],
  nonexamples: [ 'blue', 'green' ] }
compile string
addConstraint !next.exists() || next.isString()
getField on enum result: undefined { type: 'string',
  constraint: 'next.val().matches(/red/)',
  examples: [ 'red' ],
  nonexamples: [ 'blue', 'green' ] }
error line 9:13
blue
Error: nonexample erroneously passed
    at /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/schema.ts:408:88
    at /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:262:13
    at LinkedList.forEach (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/util/Collections.ts:635:17)
    at JArray.forEach (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:261:23)
    at annotate_schema (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/schema.ts:405:28)
    at annotate_schema (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/schema.ts:310:43)
    at /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/src/schema.ts:298:53
    at /Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:329:13
    at Dictionary.forEach (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/util/Collections.ts:891:27)
    at JObject.forEach (/Users/nicholasf/.nvm/versions/node/v0.12.7/lib/node_modules/blaze_compiler/node_modules/source-processor/src/source-processor.ts:328:25)
```

I'm new to blaze compiler so it may be something I've done.

Thanks,
Nicholas

**Comment by tomlarkworthy** [comment]
Constrains don't work with inline tests, due to potential data dependence.

**Comment by nicholasf** [comment]
Ah thanks. Sorry. I must have missed that when I read the docs.
